### ISSUE TITLE
Update intl dependency from ^0.17.0 to intl ^0.18.0

### ISSUE THREAD

**Issue by hurkanugur** [Enough-Software/enough_icalendar#7]
Please update the intl dependency from ^0.17.0 to intl ^0.18.0

**Comment by AyberkAhmet** [comment]
+1

**Comment by hurkanugur** [comment]
I've created a pull request for this. Hoping to see it accepted ASAP.

**Comment by AyberkAhmet** [comment]
If your job is urgent, you can use it like this.

https://github.com/Enough-Software/enough_mail/issues/210#issuecomment-1399550438

**Comment by robert-virkus** [comment]
Thanks guys and sorry for my slooooooooow reaction time here! This is now release in v0.14.0. I guess you all know that you can override dependencies with a `dependency_override` in your pubspec.yaml.
